15. Сформировать целочисленную матрицу А[n,n] с помощью генератора
случайных чисел (random). Найти в каждой строке наибольший элемент и
поменять его местами с элементом главной диагонали.
Вычислить значение медианы для элементов главной диагонали
преобразованной матрицы. Вычисление медианы выполнить двумя способами:
через стандартную функцию и через программирование формулы.

In [18]:
import numpy as np

def calculate_median_formula(sorted_arr):
    n = len(sorted_arr)
    if n % 2 == 1:
        return sorted_arr[n // 2]
    else:
        return (sorted_arr[n // 2 - 1] + sorted_arr[n // 2]) / 2

n = int(input("Введите размер матрицы n: "))

A = np.random.randint(0, 100, size=(n, n))
print("Исходная матрица:")
print(A);
print("\nГлавная диагональ:",np.diag(A))

for i in range(n):
    max_in_row = np.argmax(A[i])
    A[i, i], A[i, max_in_row] = A[i, max_in_row], A[i, i]

print("\nМатрица после замены:")
print(A)

main_diagonal = np.diag(A)

median_numpy = np.median(main_diagonal)

# Вычисление медианы по формуле
sorted_diag = np.sort(main_diagonal)
# print("\nОтсортированная диагональ: ", sorted_diag)
median_formula = calculate_median_formula(sorted_diag)

print("\nГлавная диагональ после сортировки:", main_diagonal)
print("Медиана (numpy):", median_numpy)
print("Медиана (формула):", median_formula)

Введите размер матрицы n: 4
Исходная матрица:
[[29 84  7 25]
 [71 32 84 60]
 [16 25 46 75]
 [71 86 35  4]]

Главная диагональ: [29 32 46  4]

Матрица после замены:
[[84 29  7 25]
 [71 84 32 60]
 [16 25 75 46]
 [71  4 35 86]]

Главная диагональ после сортировки: [84 84 75 86]
Медиана (numpy): 84.0
Медиана (формула): 84.0


5. Сформировать целочисленную матрицу А[n,m] с помощью генератора
случайных чисел
(random). Отсортировать по возрастанию элементы
последней строки матрицы.
Вычислить значение медианы этой строки матрицы. Вычисление
медианы выполнить двумя способами: через стандартную функцию и через
программирование формулы

In [19]:
import numpy as np

def calculate_median_formula(sorted_arr):
    n = len(sorted_arr)
    if n % 2 == 1:
        return sorted_arr[n // 2]
    else:
        return (sorted_arr[n // 2 - 1] + sorted_arr[n // 2]) / 2

n = int(input("Введите количество строк n: "))
m = int(input("Введите количество столбцов m: "))

A = np.random.randint(0, 100, size=(n, m))
print("\nИсходная матрица:")
print(A)

last_row = A[-1].copy()
A[-1] = np.sort(last_row)

print("\nМатрица после сортировки последней строки:")
print(A)

median_numpy = np.median(A[-1])
median_manual = calculate_median_formula(A[-1])

print("\nПоследняя строка после сортировки:", A[-1])
print(f"Медиана (стандартная функция NumPy): {median_numpy}")
print(f"Медиана (ручной расчёт по формуле): {median_manual}")

Введите количество строк n: 6
Введите количество столбцов m: 5

Исходная матрица:
[[69 80 24 65 99]
 [67 36 92 85 84]
 [91 21 40 84 38]
 [55 37  8 83 41]
 [32  9 55 20 70]
 [ 2 76 88 75 49]]

Матрица после сортировки последней строки:
[[69 80 24 65 99]
 [67 36 92 85 84]
 [91 21 40 84 38]
 [55 37  8 83 41]
 [32  9 55 20 70]
 [ 2 49 75 76 88]]

Последняя строка после сортировки: [ 2 49 75 76 88]
Медиана (стандартная функция NumPy): 75.0
Медиана (ручной расчёт по формуле): 75
